spring:
  datasource:
    url: jdbc:mysql://eucomida-mysql:3306/eucomida_db?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: eucomida_user
    password: eucomida_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
logging:
  level:
    '[org.hibernate.orm.connections.pooling]': warn