spring:
  datasource:
    url: jdbc:mysql://eucomida-mysql:3306/eucomida_db?serverTimezone=UTC
    username: eucomida_user
    password: eucomida_pass
  jpa:
    open-in-view: false
    show-sql: true
  messages:
    basename: ValidationMessages
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks


logging:
  level:
    '[org.hibernate.orm.connections.pooling]': warn