spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eucomida_db?serverTimezone=UTC
    username: eucomida_user
    password: eucomida_pass
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:db/migration
  messages:
    basename: ValidationMessages

logging:
  level:
    '[org.hibernate.orm.connections.pooling]': warn